[package]
name = "modern-reaction-test"
version = "0.1.2"
edition = "2021"

[dependencies]
bevy = { version = "0.16.1", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_image",
    "bevy_ui",
    "bevy_text",
    "bevy_asset",
    "bevy_scene",
    "bevy_state",
    "bevy_gltf",
    "tonemapping_luts",
    "default_font",
    "bevy_audio",
    "png",
    "vorbis",
] }
rand = "0.8"
rayon = "1.11.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
log = "0.4.27"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[[bin]]
name = "modern-reaction-test"
path = "src/main.rs"
